version: '3.8'
services:
  cumbuca:
    image: andridus/cumbuca
    build:
      context: ..
      dockerfile: _docker/Dockerfile.dev
      no_cache: false
      args:
        user_id: ${USER}
        group_id: ${GROUP}
    command: bash
    tty: true
    stdin_open: true
    env_file: ./dev.env
    ports:
      - 4001:4000
    depends_on:
      - db
    volumes:
      - "../:/opt/app"

  db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENCODING: UTF8
      POSTGRES_BD: cumbuca_dev
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRESQL_ENABLE_TLS: 'yes'
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "6001:5432"
volumes:
  pgdata:
