ARG ELIXIR_VERSION=1.14.5
ARG OTP_VERSION=26.0
ARG DEBIAN_VERSION=bullseye-20230227-slim
ARG APP=cumbuca
ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE}

ENV TERM=xterm
ENV LANG=en_us.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV APP_PATH="/opt/app"
ENV APP_NAME=${APP}
ENV HTTP_PORT="4001"
ENV MIX_ENV="dev"

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git libstdc++6 openssl libncurses5 locales && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
  mix local.rebar --force

# copy source files
COPY ../ $APP_PATH/$APP_NAME
WORKDIR $APP_PATH/$APP_NAME
EXPOSE $HTTP_PORT

CMD ["mix","phx.server"]